blank_issues_enabled: false
contact_links:
  - name:  砖转 转
    url: https://github.com/yanivmizrachiy/botteddy/discussions
    about: 砖 砖转  拽砖 注专 拽
  - name:  爪专 拽砖专
    url: mailto:yanivmiz77@gmail.com
    about: 爪专 拽砖专 砖专 注 驻转

